import album01 from './pippi_langkous'
import album02 from './ernst_bobbie_en_de_rest'
import album03 from './sinterklaas'
import album04 from './zwarte_piet'
import album05 from './ome_willem'
import album06 from './bassie_en_adriaan'
import album07 from './swiebertje'
import album08 from './pipo_de_clown'
import album09 from './kabouter_plop'
import album10 from './samson_en_gert'
// import album11 from './stoomboot'
import album12 from './piet_piraat'
import album13 from './brum'

export default [album01, album02, album03, album04, album05, album06, album07, album08, album09, album10, /*album11,*/ album12, album13]
